In [1]:
import numpy as np
import seaborn as ssns
import pandas as pd
import scipy.stats as stats
from pydataset import data
import matplotlib.pyplot as plt
import env

### Ace Realty wants to determine whether the average time it takes to sell homes is different for its two offices. A sample of 40 sales from office #1 revealed a mean of 90 days and a standard deviation of 15 days. A sample of 50 sales from office #2 revealed a mean of 100 days and a standard deviation of 20 days. Use a .05 level of significance.

In [ ]:
# H0 Avg TTSell @ office 1 == AVG TTSell @ office 2
# Ha Avg TTSell @ office 1 != AVG TTSell @ office 2

In [ ]:
alpha = 0.05

In [ ]:
# vissualize distributions

x = np.arange(50, 150)

y1 = stats.norm(90, 15).pdf(x)
y2 = stats.norm(100, 20).pdf(x)

plt.plot(x, y1, label = 'office 1')
plt.plot(x, y2, label = 'office 2')
plt.axvline(90, ls = ':')
plt.axvline(100, ls = ':', color = 'orange')
plt.legend()

In [ ]:
t, p = stats.ttest_ind_from_stats(90,15,40,100,20,50, equal_var = False)
t, p

In [ ]:
if p < alpha:
    print('We reject null hypothesis.')
else:
    print('We fail to reject null hypothesis.')

In [ ]:
mpg = data('mpg')

In [ ]:
mpg.head()

In [ ]:
# H_0: There is no difference in fuel-efficiency in cars from 2008 and 1999
# H_a: There is a difference in fuel-efficiency in cars from 2008 and 1999

In [ ]:
mpg['avg_fe'] = stats.hmean(mpg[['cty', 'hwy']], axis = 1)
mpg.head()

In [ ]:
fe_2008 = mpg[mpg.year ==2008].avg_fe
fe_1999 = mpg[mpg.year ==1999].avg_fe

In [ ]:
fe_2008.hist()

In [ ]:
fe_1999.hist()

In [ ]:
fe_2008.count(), fe_1999.count()

In [ ]:
fe_2008.var(), fe_1999.var()

In [ ]:
stats.levene(fe_2008, fe_1999)

In [ ]:
t, p = stats.ttest_ind(fe_2008, fe_1999)
t, p

In [ ]:
if p<alpha:
    print('reject null')
else:
    print('fail to reject null')

In [ ]:
fe_2008.mean(), fe_1999.mean()

### b. Are compact cars more fuel-efficient than the average car?

In [ ]:
# H_0: MPG for compact cars <= mpg for the average car
# H_a: MPG for compact cars > mpg for the average car

# CORRELATION EXC.

Use the telco_churn data. Does tenure correlate with monthly charges? Total charges? What happens if you control for phone and internet service?

In [2]:
df = pd.read_csv('telco_churn.csv')
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [3]:
df = df.dropna()

In [ ]:
#Does tenure correlate with monthly charges

df.plot.scatter(y = 'MonthlyCharges', x = 'tenure')

# no correlation

In [ ]:
# Doess tenure correlate to total charges?

df.plot.scatter(y = 'TotalCharges', x = 'tenure')